application: your-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: "2.5.1"

handlers:
- url: /.*
  script: main.app

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.md
- ^(.*/)?\..*
